/* codegen.c — AST to C code emitter for TinyC-Lite */
#include "codegen.h"
#include <stdio.h>

/* ══════════════════════════════════════════════
   PART 1 — Expression emitter
   Turns expression nodes into C expressions
   ══════════════════════════════════════════════ */

/* Forward declaration — emit_expr calls itself recursively */
static void emit_expr(Node *n, FILE *out);

static void emit_expr(Node *n, FILE *out) {
    if (!n) return;

    switch (n->type) {

        case NODE_NUM:
            /* Integer literal — just print the number */
            fprintf(out, "%d", n->ival);
            break;

        case NODE_IDENT:
            /* Variable name — just print the name */
            fprintf(out, "%s", n->name);
            break;

        case NODE_BINOP:
            /* Binary operation: (left OP right)
               Always wrap in parens — avoids any
               precedence issues in the output C code */
            fprintf(out, "(");
            emit_expr(n->children[0], out);   /* left  */
            fprintf(out, " %s ", n->name);    /* op: + - * / */
            emit_expr(n->children[1], out);   /* right */
            fprintf(out, ")");
            break;

        case NODE_UNARY:
            /* Unary minus: (-expr) */
            fprintf(out, "(-");
            emit_expr(n->children[0], out);
            fprintf(out, ")");
            break;

        case NODE_COMPARE:
            /* Comparison: left OP right
               e.g.  x > 5   or   y == 10  */
            emit_expr(n->children[0], out);
            fprintf(out, " %s ", n->name);    /* > < == != >= <= */
            emit_expr(n->children[1], out);
            break;

        default:
            fprintf(stderr,
                "codegen error: unexpected expr node type %d\n",
                n->type);
            break;
    }
}

/* ══════════════════════════════════════════════
   PART 2 — Statement emitter
   Turns statement nodes into C statements
   depth controls how many spaces to indent
   ══════════════════════════════════════════════ */

/* emit_indent: print (depth * 4) spaces */
static void emit_indent(int depth, FILE *out) {
    for (int i = 0; i < depth * 4; i++)
        fprintf(out, " ");
}

/* Forward declaration */
static void emit_stmt(Node *n, FILE *out, int depth);

static void emit_stmt(Node *n, FILE *out, int depth) {
    if (!n) return;

    switch (n->type) {

        case NODE_PROGRAM:
            /* A list of statements — emit each one */
            for (int i = 0; i < n->nchildren; i++)
                emit_stmt(n->children[i], out, depth);
            break;

        case NODE_VARDECL:
            /* int x = expr; */
            emit_indent(depth, out);
            fprintf(out, "int %s = ", n->name);
            emit_expr(n->children[0], out);
            fprintf(out, ";\n");
            break;

        case NODE_ASSIGN:
            /* x = expr; */
            emit_indent(depth, out);
            fprintf(out, "%s = ", n->name);
            emit_expr(n->children[0], out);
            fprintf(out, ";\n");
            break;

        case NODE_PRINT:
            /* print expr;  →  printf("%d\n", expr); */
            emit_indent(depth, out);
            fprintf(out, "printf(\"%%d\\n\", ");
            emit_expr(n->children[0], out);
            fprintf(out, ");\n");
            break;

        case NODE_IF:
            /* if (cond) { ... } else { ... } */
            emit_indent(depth, out);
            fprintf(out, "if (");
            emit_expr(n->children[0], out);   /* condition */
            fprintf(out, ") {\n");

            /* then-block — indent one level deeper */
            emit_stmt(n->children[1], out, depth + 1);

            emit_indent(depth, out);
            fprintf(out, "}");

            /* optional else-block */
            if (n->nchildren > 2) {
                fprintf(out, " else {\n");
                emit_stmt(n->children[2], out, depth + 1);
                emit_indent(depth, out);
                fprintf(out, "}");
            }
            fprintf(out, "\n");
            break;

        default:
            break;
    }
}

/* ══════════════════════════════════════════════
   PART 3 — Public entry point
   Writes the full C file: includes + main() + body
   ══════════════════════════════════════════════ */

void codegen(Node *root, FILE *out) {
    /* File header */
    fprintf(out, "/* Generated by tcc — TinyC-Lite Compiler */\n");
    fprintf(out, "#include <stdio.h>\n\n");

    /* Wrap everything in main() */
    fprintf(out, "int main(void) {\n");

    /* Emit all statements at indent level 1 */
    emit_stmt(root, out, 1);

    /* Close main */
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}